<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="UFT-8"/>';
echo '<meta name="description" content=" This is placed under the main url as info/">';
echo '<title>EMERGENCY</title>';
echo '<style></style>';
echo '<script></script>';
echo '';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">';
echo '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">';
echo '<link rel="stylesheet" href="style.css">';
echo '</head>';
echo '<header class="hospital">';
echo '<body >';
echo '<nav class="navigation-bar">';
echo '<img class="logo" src="finalhelpful1.png">';
echo '<a href="home.html">Home</a>';
echo '<a href="MedicalHelp.html">HOSPITALS</a>';
echo '<a href="nursingmanager.html">NURSING HOUSE</a>';
echo '<a href="sheltersManager.html">SHELTER</a>';
echo '<a href="donations.html">DONATIONS</a>';
echo '</nav>';
echo '';
echo '<!-- <div class="pic"> -->';
echo '<img src="flat1.jpg"      alt="Not Found" width="100%" height="400px">';
echo '';
echo '<!-- </div> -->';
echo '';
echo '';
echo '';
echo '';
echo '<div class="text2">';
echo '<h1> Get Help</h1>';
echo '<p> with our proffessional team 24/7 , all you need is to fill the following form :   </p>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<div class="signupFrm">';
echo '<form action="/action_page.php" class="form">';
echo '<h1 class="title"><img id="logo" src="finalhelpful1.png"></h1>';
echo '';
echo '<div class="inputContainer">';
echo '<input type="text" name="username" class="input" placeholder="Name"  required >';
echo '<!-- <label for="" class="label">Name</label> -->';
echo '</div>';
echo '';
echo '<div class="inputContainer">';
echo '<input type="text" name="ID" class="input" placeholder="ID"  required >';
echo '<!-- <label for="" class="label">ID</label> -->';
echo '</div>';
echo '';
echo '<div class="inputContainer">';
echo '<input type="text" name="Phone" class="input" placeholder="Phone"  required>';
echo '<!-- <label for="" class="label">Phone</label> -->';
echo '</div>';
echo '';
echo '<div class="inputContainer">';
echo '<!-- <input type="text" class="input" placeholder="Subject"> -->';
echo '<textarea id="subject"  placeholder="Leave a note.." style="height:100px"></textarea>';
echo '<!-- <label for="" class="label"></label> -->';
echo '</div>';
echo '<!-- <a href="#myModal" class="trigger-btn" data-toggle="modal"> -->';
echo '<!-- <button class="boxlogin" type="submit">Sign in</button> -->';
echo '<input type="submit" class="submitBtn"  id="submit" >';
echo '<!-- </a>';
echo '<div id="myModal" class="modal fade">';
echo '<div class="modal-dialog modal-confirm">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<div class="icon-box">';
echo '<i class="material-icons">&#xE876;</i>';
echo '</div>';
echo '<h4 class="modal-title w-100">Awesome!</h4>';
echo '</div>';
echo '<div class="modal-body">';
echo '<p class="text-center">Your booking has been confirmed. Check your email for detials.</p>';
echo '</div>';
echo '<div class="modal-footer">';
echo '<button class="btn btn-success btn-block" data-dismiss="modal">OK</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '</form>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '<footer class="footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="footer-col">';
echo '<h4>company</h4>';
echo '<ul>';
echo '<li><a href="#">about us</a></li>';
echo '<li><a href="#">our services</a></li>';
echo '<li><a href="#">privacy policy</a></li>';
echo '<li><a href="#">affiliate program</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="footer-col">';
echo '<h4>get help</h4>';
echo '<ul>';
echo '<li><a href="#">FAQ</a></li>';
echo '<li><a href="#">shipping</a></li>';
echo '<li><a href="#">returns</a></li>';
echo '<li><a href="#">order status</a></li>';
echo '<li><a href="#">payment options</a></li>';
echo '</ul>';
echo '</div>';
echo '';
echo '<div class="footer-col">';
echo '<h4>follow us</h4>';
echo '<div class="social-links">';
echo '<a href="#"><i class="fab fa-facebook-f"></i></a>';
echo '<a href="#"><i class="fab fa-twitter"></i></a>';
echo '<a href="#"><i class="fab fa-instagram"></i></a>';
echo '<a href="#"><i class="fab fa-linkedin-in"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '</body>';
echo '<script src="main.js"></script>';
echo '<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>';
echo '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>';
echo '</header>';
echo '';
echo '';
echo '</html>';
echo '';
?>